package com.changsune.changsu.yeontalk_kotlin

object Constants {

    var DEVICE_ID = ""

    var CURRENT_YEAR_PLUS_ONE: Int? = 2020

    var LOAD_LIMIT = "30"

    var AGE_KOREAN = "세"

    // SHAREDPREF_KEY_SETTING
    var SHAREDPREF_KEY_SETTING = "SHAREDPREF_KEY_SETTING"
    var SHAREDPREF_KEY_SETTING_GENDER = "SHAREDPREF_KEY_SETTING_GENDER"
    var SHAREDPREF_KEY_SETTING_MAX_AGE = "SHAREDPREF_KEY_SETTING_MAX_AGE"
    var SHAREDPREF_KEY_SETTING_MIN_AGE = "SHAREDPREF_KEY_SETTING_MIN_AGE"
    var SHAREDPREF_KEY_SETTING_NATION = "SHAREDPREF_KEY_SETTING_NATION"
    var SHAREDPREF_KEY_SETTING_REGION = "SHAREDPREF_KEY_SETTING_REGION"


    // SHAREDPREF_KEY_PROFILE
    var SHAREDPREF_KEY_PROFILE = "SHAREDPREF_KEY_PROFILE"
    var SHAREDPREF_KEY_PROFILE_USER_ID = "SHAREDPREF_KEY_PROFILE_USER_ID"
    var SHAREDPREF_KEY_PROFILE_NICKNAME = "SHAREDPREF_KEY_PROFILE_NICKNAME"
    var SHAREDPREF_KEY_PROFILE_GENDER = "SHAREDPREF_KEY_PROFILE_GENDER"
    var SHAREDPREF_KEY_PROFILE_BIRTHYEAR = "SHAREDPREF_KEY_PROFILE_BIRTHYEAR"
    var SHAREDPREF_KEY_PROFILE_NATION = "SHAREDPREF_KEY_PROFILE_NATION"
    var SHAREDPREF_KEY_PROFILE_REGION = "SHAREDPREF_KEY_PROFILE_REGION"
    var SHAREDPREF_KEY_PROFILE_IMAGE = "SHAREDPREF_KEY_PROFILE_IMAGE"
    var SHAREDPREF_KEY_PROFILE_INSTRODUCTION = "SHAREDPREF_KEY_PROFILE_INSTRODUCTION"
    var SHAREDPREF_KEY_PROFILE_POINT = "SHAREDPREF_KEY_PROFILE_POINT"

    // Chat Type
    var CHAT_TYPE = "CHAT"
    var IMAGE_TYPE = "IMAGE"
    var VIDEO_TYPE = "VIDEO"
    var VIDEO_CALL_TYPE = "VIDEO_CALL"
    var EXIT_TYPE = "EXIT"

}